CREATE TABLE "user" (
  "id" uuid PRIMARY KEY NOT NULL,
  "activation_token" char32,
  "email" varchar UNIQUE NOT NULL,
  "email_notifications" boolean DEFAULT true,
  "name" varchar NOT NULL,
  "passwordhash" char97 NOT NULL
);

CREATE TABLE "folder" (
  "id" uuid PRIMARY KEY NOT NULL,
  "user_id" uuid NOT NULL,
  "name" varchar NOT NULL,
  "parent_folder_id" uuid
);

CREATE TABLE "record" (
  "id" uuid PRIMARY KEY NOT NULL,
  "folder_id" uuid NOT NULL,
  "category_id" integer NOT NULL,
  "amount" decimal(10,2),
  "company_name" varchar,
  "coupon_code" varchar,
  "description" text,
  "exp_date" date,
  "last_accessed_at" timestamp,
  "notify_on" boolean DEFAULT false,
  "product_id" varchar,
  "purchase_date" timestamptz,
  "warranty_exp" date
);

CREATE TABLE "file" (
  "id" uuid PRIMARY KEY NOT NULL,
  "record_id" uuid NOT NULL,
  "description" text,
  "document_date" date,
  "file_key" varchar UNIQUE NOT NULL,
  "is_starred" boolean DEFAULT false,
  "name" varchar NOT NULL,
  "ocr_data" text
);

CREATE TABLE "category" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "color" varchar,
  "icon" varchar,
  "name" varchar UNIQUE NOT NULL
);

ALTER TABLE "category" ADD FOREIGN KEY ("id") REFERENCES "record" ("category_id");

ALTER TABLE "file" ADD FOREIGN KEY ("record_id") REFERENCES "record" ("id") ON DELETE SET NULL;

ALTER TABLE "folder" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE;

ALTER TABLE "folder" ADD FOREIGN KEY ("parent_folder_id") REFERENCES "folder" ("id") ON DELETE CASCADE;

ALTER TABLE "record" ADD FOREIGN KEY ("folder_id") REFERENCES "folder" ("id") ON DELETE CASCADE;
